`use strict`;

const searchHistoryData = [
  "attack on titan",
  "avengers",
  "amazon",
  "anime",
  "alibaba",
  "armstrong number",
  "black hole",
  "big bang",
  "black clover new season release date",
  "bungo stray dogs",
  "battle ground",
  "bmw",
  "coding ninja",
  "call of duty",
  "charlotte",
  "chess.com",
  "chinese food",
  "cheese pizza",
  "demon slayer new episode release date",
  "dragon ball super",
  "difference between for and while loop",
  "dbms",
  "differentiation",
  "death note",
  "elephant",
  "entropy of universe",
  "ebay",
  "epsilon",
  "editor",
  "flipkart",
  "facebook",
  "fastest thing in universe",
  "fedex",
  "fibonacci series",
  "ferrari",
  "ford",
  "firefox",
  "google",
  "gmail",
  "google chat",
  "google meet",
  "gitlab",
  "github",
  "git download",
  "garena free fire",
  "how to become a programmer in 5 min",
  "how to learn javascript in 2 min",
  "how to become web designer in 2 seconds",
  "how to become a software engineer in the blink of an eye",
  "how to get started with git",
  "how to download visual studio code",
  "how to sort the array of nested objects in javascript",
  "indian flag",
  "indian food",
  "instagram",
  "internet",
  "india",
  "indian map",
  "integration",
  "javascript",
  "java",
  "jee mains",
  "jsfiddle",
  "kinetic energy of a moving body",
  "kfc",
  "kinetic theory of gases",
  "knight rider",
  "kimetsu no yaiba",
  "light",
  "laptop",
  "location",
  "linkedin",
  "lucknow university",
  "latest news",
  "make my trip",
  "most commonly used programming language",
  "music",
  "most important topic in javascript",
  "microsoft",
  "metaverse",
  "network",
  "newton's law of universal gravitation",
  "netflix",
  "notepad",
  "number of atoms present in the universe",
  "nested objects in javascript",
  "ola",
  "oracle",
  "one drive",
  "outlook",
  "mingw download",
  "ookla speed test",
  "online gdb",
  "one punch man",
  "pinterest",
  "pc games",
  "python",
  "pubg",
  "palindrom",
  "post office",
  "play station",
  "quora",
  "quotes",
  "quiz on javascript",
  "qr code scanner online",
  "realme",
  "redmi",
  "railway enquiry",
  "recuva",
  "red panda",
  "raspberry pi",
  "samsung",
  "spotify",
  "state bank of india",
  "tallest building in the world",
  "tata",
  "telegram",
  "tokyo ghoul",
  "tesla",
  "tata consultancy services",
  "universe",
  "united states",
  "united nations organization",
  "universal gravitational constant",
  "vectoscalar technologies",
  "vector quantity",
  "visual studio code",
  "visible light",
  "volume of universe",
  "vaccine",
  "viscosity",
  "what is viscosity",
  "whatsapp",
  "who is the richest person alive",
  "what is your name?",
  "what is the significance of closures in javascript",
  "what is asynchronous programming",
  "xerox",
  "youtube",
  "yahoo",
  "yes bank",
  "zoom meeting",
  "zoo",
  "zebra",
  "zero",
  "seraph of the end",
  "steins gate"
];
